### ISSUE TITLE
Input fields in attribute editor do not reflect component settings

### ISSUE THREAD

**Issue by pcsandford** [Rise-Vision/rise-slides#26]
**What should happen**
When the slides presentation is opened in the attribute editor the user should see the default settings for the slides url and the transition time.

**What currently happens**
The slides url shows the placeholder text with green checkmark and the transition time shows 10 (although the presentation is set to change slides every 6 second)

**Steps to recreate**
Add the 'Full Screen Google Slides' Template from the Templates Account. The component settings are set to display the slides and transition every 6s but the input fields will show the placeholder text. You can also try adding the 'Testing Slides' Template - the url also shows the placeholder text.

Thanks!

**Comment by andrecardoso** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[rise-slides issue #26] Input fields in attribute editor do not reflect component settings](https://trello.com/c/8rxq6JkS/150-rise-slides-issue-26-input-fields-in-attribute-editor-do-not-reflect-component-settings)

**Comment by andrecardoso** [comment]
Fixed in https://github.com/Rise-Vision/rise-vision-apps/pull/1095
