### ISSUE TITLE
Black border shows on bottom and left of preview

### ISSUE THREAD

**Issue by pcsandford** [Rise-Vision/rise-slides#27]
**What should happen**

Full screen slides in preview should not show a border.

**What currently happens**

Full screen slides in preview shows a small black border on the right and bottom of the preview. Borders do not show when run on the display.

**Steps to recreate**

Add the Full Screen Slides Template and you will see the borders in preview. Slides are set to 16:9 so should match the ratio of the preview window. We have also tested setting the slides to 1920px x 1080px with the same results.

**Comment by andrecardoso** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[rise-slides issue #27] Black border shows on bottom and left of preview](https://trello.com/c/FfUcdXtu/152-rise-slides-issue-27-black-border-shows-on-bottom-and-left-of-preview)

**Comment by olegrise** [comment]
@pcsandford could you make a screenshot of what you mean. Also in the title of the issue it says "bottom and left" and then in description "right and bottom".

**Comment by andrecardoso** [comment]
@olegrise I don't know if it helps, but I believe this is the same as https://github.com/Rise-Vision/rise-slides/issues/28 and there's a screenshot there :-)

**Comment by olegrise** [comment]
@andrecardoso Thanks! That is exactly what I need.

**Comment by olegrise** [comment]
The border is rendered by Google Slides and we don't have any control over it. 
I played with different option including removing [CSS scaling](https://github.com/Rise-Vision/rise-vision-apps/blob/71cca55b68741208a3d6a66802f1f10aec2ac596/web/scripts/template-editor/directives/dtv-editor-preview-holder.js#L113), but it makes no difference. I'm running out of ideas what else to try. 
BTW, other people also [complain about this issue](https://support.google.com/sites/thread/5215181?hl=en).

**Comment by andrecardoso** [comment]
Closing this per @olegrise 's comment
