### ISSUE TITLE
Black border shows on left and bottom of slide.

### ISSUE THREAD

**Issue by RowanDarlison** [Rise-Vision/rise-slides#28]
A small black border is showing. When I edit the .punch-viewer-content width and height attributes the black border disappears however it cannot be edited outside of the console.  See the attached images.
![img1](https://user-images.githubusercontent.com/12125461/60623727-57d72300-9db1-11e9-9d9e-d23a3f908056.jpg)
![img2](https://user-images.githubusercontent.com/12125461/60623728-57d72300-9db1-11e9-903e-edc3ac31a337.jpg)
![img3](https://user-images.githubusercontent.com/12125461/60623729-57d72300-9db1-11e9-8d92-c4c467f65b3d.jpg)

**Comment by olegrise** [comment]
@RowanDarlison I believe this is a duplicate fo the #27. Thanks.
