### ISSUE TITLE
No mention of script tag in Google Slides component documentation

### ISSUE THREAD

**Issue by clairehansen12** [Rise-Vision/rise-slides#39]
The readme file for the Google Slides component doesn't mention that a script tag needs to be included for it to work. 

This issue can be fixed by adding a section to the documentation that explains how to add it, similar to this: https://github.com/Rise-Vision/rise-data-counter#integration-in-a-template

Thanks!

**Comment by santiagonoguez** [comment]
Missing documentation added: https://github.com/Rise-Vision/rise-slides/pull/40
